### ISSUE TITLE
discord api error

### ISSUE THREAD

**Issue by orfox32** [onepiecehung/discord.js-temporary-channel#2]
how do i fix discord api error ?

**Comment by orfox32** [comment]
sometimes it wont delete my vc and receive an error code which is discord api error even tho i have a a correct parent id

**Comment by onepiecehung** [comment]
@orfox32 I didn't see this error before, can you provide your discord.js version?

**Comment by orfox32** [comment]
discord.js @12.5.1

**Comment by orfox32** [comment]
`client.on('voiceStateUpdate', (oldMember, newMember) => {
            let isLeave = (oldMember.channel != undefined)

            if (isLeave) {
                console.log(isLeave);
                if (oldMember.channel.name.startsWith('🤡 ')) {
                    if (oldMember.channel.members.size == 0) {
                        oldMember.channel.delete()
                    }
                    else { 
                        let matchMember = oldMember.channel.members.find(x => `${x.displayName}` == oldMember.channel.name);
                        if (matchMember == null) {
                            oldMember.channel.setName(`🤡 ${oldMember.channel.members.random().displayName}'s Room`)
                        }
                    }
                }
            }

            if (newMember.channel != null && newMember.channel.name.startsWith('👻 ')) {
                newMember.guild.channels.create(`🤡 ${newMember.member.user.username}'s Room`, {
                    type: "voice",
                    parent: '809723111477346304',
                }).then(cloneChannel => newMember.setChannel(cloneChannel))
            }
        });
`

**Comment by orfox32** [comment]
that's my code

**Comment by onepiecehung** [comment]
@orfox32 try follow this code
```js
if (newMember.channel != null && newMember.channel.name.startsWith('👻 ')) {
            newMember.guild.channels.create(`🤡 ${newMember.member.user.username}'s Room`, {
                type: "voice",
                parent: newMember.channel.parent,
            }).then(cloneChannel => newMember.setChannel(cloneChannel))
}
```

Use `parent` **dynamic** not **static**

**Comment by orfox32** [comment]
ok ok thanks

**Comment by orfox32** [comment]
i will tell you if the error comebacks or not

**Comment by orfox32** [comment]
it shows error again even tho i followed your instructions same error

**Comment by onepiecehung** [comment]
@orfox32 
1: Did you provide permission for the bot
2: Can you show an error log

**Comment by orfox32** [comment]
`this is the error code (node:33) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Channel at RequestHandler.execute (/home/runner/Create/node_modules/discord.js/src/rest/RequestHandler.js:154:13) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async RequestHandler.push (/home/runner/Create/node_modules/discord.js/src/rest/RequestHandler.js:39:14) at async VoiceChannel.edit (/home/runner/Create/node_modules/discord.js/src/structures/GuildChannel.js:355:21) (node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)` and i have a admin role for the bot and also manage channel and view channel

**Comment by onepiecehung** [comment]
@orfox32 I'll review and fix it in the future. You can search for this error on the internet, I see some result same this error.

**Comment by orfox32** [comment]
let me know if you fix this issue thanks <3

**Comment by onepiecehung** [comment]
@orfox32 today I found this error, I think you don't need to care about it, you can skip this error

**Comment by orfox32** [comment]
> @orfox32 today I found this error, I think you don't need to care about it, you can skip this error

how ?

**Comment by onepiecehung** [comment]
@orfox32 I found this error when I watching my tutorial: https://www.youtube.com/watch?v=FcndgZA2E4E

**Comment by orfox32** [comment]
> @orfox32 I found this error when I watching my tutorial: https://www.youtube.com/watch?v=FcndgZA2E4E

so ok i will try to find out what is causing the error

**Comment by onepiecehung** [comment]
@orfox32 Fixed it with redis, plz check this code
```ts
client.on(
    "voiceStateUpdate",
    async (oldMember: VoiceState | any, newMember: VoiceState | any) => {
        // ! leave
        const isLeave = oldMember.channel != undefined;
        // todo: check member leave
        if (isLeave) {
            if (
                oldMember.channel.name.startsWith(settings.nameStartsWithTemp)
            ) {
                switch (oldMember.channel.members.size) {
                    case 0:
                        const isRemoveVC = await REDIS.getKey(
                            `isRemoveVC:${oldMember.channel.id}`
                        );

                        if (!isRemoveVC) {
                            oldMember.channel.delete(
                                "Remove voice channel, cause no one is in the voice channel"
                            );
                            await REDIS.deleteKey(
                                `ownerId:${oldMember.channel.id}`
                            );
                            await REDIS.deleteKey(
                                `guildId:${oldMember.channel.id}`
                            );
                        }
                        await REDIS.deleteKey(
                            `isRemoveVC:${oldMember.channel.id}`
                        );

                        break;

                    case 1:
                        const isBot = oldMember.channel.members.find(
                            (x: any) => x.user.bot == true
                        );
                        if (isBot) {
                            oldMember.channel.delete(
                                "Remove voice channel, cause only bots in voice channel"
                            );
                            await REDIS.setKey(
                                `isRemoveVC:${oldMember.channel.id}`,
                                true
                            );
                            await REDIS.deleteKey(
                                `ownerId:${oldMember.channel.id}`
                            );
                            await REDIS.deleteKey(
                                `guildId:${oldMember.channel.id}`
                            );
                        } else {
                            // todo: change name
                            const matchMember = oldMember.channel.members.find(
                                (x: any) =>
                                    `${settings.nameStartsWithTemp}${x.displayName}` ==
                                    oldMember.channel.name
                            );
                            if (matchMember == null) {
                                oldMember.channel.setName(
                                    `${settings.nameStartsWithTemp}${
                                        oldMember.channel.members.random()
                                            .displayName
                                    }`
                                );
                                await REDIS.deleteKey(
                                    `ownerId:${oldMember.channel.id}`
                                );
                                await REDIS.deleteKey(
                                    `guildId:${oldMember.channel.id}`
                                );
                            }
                        }
                        break;

                    default:
                        // todo: change name
                        const matchMember = oldMember.channel.members.find(
                            (x: any) =>
                                `${settings.nameStartsWithTemp}${x.displayName}` ==
                                oldMember.channel.name
                        );
                        if (matchMember == null) {
                            oldMember.channel.setName(
                                `${settings.nameStartsWithTemp}${
                                    oldMember.channel.members.random()
                                        .displayName
                                }`
                            );
                            await REDIS.deleteKey(
                                `ownerId:${oldMember.channel.id}`
                            );
                            await REDIS.deleteKey(
                                `guildId:${oldMember.channel.id}`
                            );
                        }
                        break;
                }
            }
        }

        // todo create channel
        if (
            newMember.channel != null &&
            newMember.channel.name.startsWith(settings.nameStartsWith)
        ) {
            newMember.guild.channels
                .create(
                    `${settings.nameStartsWithTemp}${newMember.member.user.username}`,
                    {
                        type: "voice",
                        parent: newMember.channel.parent,
                        userLimit: settings.userLimit,
                        reason: settings.reason,
                    }
                )
                .then(async (cloneChannel: any) => {
                    newMember.setChannel(cloneChannel);
                    await REDIS.setKey(
                        `ownerId:${cloneChannel.id}`,
                        newMember.id
                    );
                    await REDIS.setKey(
                        `guildId:${cloneChannel.id}`,
                        newMember.guild.id
                    );
                });
        }
    }
);
```
